In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [ ]:
data = pd.read_csv("splice.data", header=None)

data.columns = ["class", "id", "sequence"]

data.head()

,class,id,sequence
0,EI,ATRINS-DONOR-521,CCAGCTGCATCACAGGAGGCCAGCGAGCAGG...
1,EI,ATRINS-DONOR-905,AGACCCGCCGGGAGGCGGAGGACCTGCAGGG...
2,EI,BABAPOE-DONOR-30,GAGGTGAAGGACGTCCTTCCCCAGGAGCCGG...
3,EI,BABAPOE-DONOR-867,GGGCTGCGTTGCTGGTCACATTCCTGGCAGGT...
4,EI,BABAPOE-DONOR-2817,GCTCAGCCCCCAGGTCACCCAGGAACTGACGTG...

In [ ]:
data['sequence'] = data['sequence'].str.replace(" ", "")
data = data.drop("id", axis=1)

data.head()

  class                                           sequence
0    EI  CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...
1    EI  AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...
2    EI  GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...
3    EI  GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...
4    EI  GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...

In [ ]:
import numpy as np

mapping = {
    'A':[1,0,0,0],
    'C':[0,1,0,0],
    'G':[0,0,1,0],
    'T':[0,0,0,1],
    'N':[0,0,0,0]
}

def encode_seq(seq):
    encoded = []
    
    for char in seq:
        encoded.extend(mapping.get(char,[0,0,0,0]))
    
    return encoded

X = data['sequence'].apply(encode_seq)
X = np.array(X.tolist())

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(data['class'])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

for i in [500, 1000, 2000, 5000, 10000]:
    
    model = LogisticRegression(max_iter=i)
    
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    
    acc = accuracy_score(y_test, y_pred)
    
    print("max_iter:", i, "Accuracy:", acc)

max_iter: 500 Accuracy: 0.9404388714733543
max_iter: 1000 Accuracy: 0.9404388714733543
max_iter: 2000 Accuracy: 0.9404388714733543
max_iter: 5000 Accuracy: 0.9404388714733543
max_iter: 10000 Accuracy: 0.9404388714733543

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.94      0.93       179
           1       0.91      0.93      0.92       140
           2       0.97      0.94      0.96       319

    accuracy                           0.94       638
   macro avg       0.93      0.94      0.93       638
weighted avg       0.94      0.94      0.94       638

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=10)

print("Cross Validation Accuracy:", scores.mean())

Cross Validation Accuracy: 0.9401253918495296